--
-- PostgreSQL database dump
--

-- Dumped from database version 17.5 (Debian 17.5-1)
-- Dumped by pg_dump version 17.5 (Debian 17.5-1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: public; Type: SCHEMA; Schema: -; Owner: -
--

-- *not* creating schema, since initdb creates it


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: bookings; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.bookings (
    id bigint NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    end_date timestamp(6) without time zone NOT NULL,
    number_of_guests integer,
    special_requests character varying(500),
    start_date timestamp(6) without time zone NOT NULL,
    status character varying(255) NOT NULL,
    "timestamp" timestamp(6) without time zone NOT NULL,
    total_price double precision NOT NULL,
    updated_at timestamp(6) without time zone NOT NULL,
    room_id bigint NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: bookings_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.bookings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.bookings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: notification_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.notification_tokens (
    id bigint NOT NULL,
    app_version character varying(50),
    created_at timestamp(6) without time zone,
    device_id character varying(255),
    device_model character varying(100),
    fcm_token character varying(500) NOT NULL,
    is_active boolean,
    os_version character varying(50),
    updated_at timestamp(6) without time zone,
    user_id bigint NOT NULL
);


--
-- Name: notification_tokens_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.notification_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room_amenities; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_amenities (
    room_id bigint NOT NULL,
    amenity character varying(255)
);


--
-- Name: room_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_images (
    room_id bigint NOT NULL,
    image character varying(255)
);


--
-- Name: room_rules; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room_rules (
    room_id bigint NOT NULL,
    rule character varying(255)
);


--
-- Name: properties; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.properties (
    id bigint NOT NULL,
    address character varying(255),
    contact_email character varying(255),
    contact_phone character varying(255),
    contract_url character varying(255),
    created_at timestamp(6) without time zone,
    description character varying(255),
    has_contract boolean,
    has_video boolean,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    owner_id bigint,
    owner_name character varying(255),
    property_type character varying(255),
    title character varying(255),
    updated_at timestamp(6) without time zone,
    video_url character varying(255)
);

--
-- Name: properties_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.properties ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.properties_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: property_images; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.property_images (
    property_id bigint NOT NULL,
    image character varying(255)
);

--
-- Name: rooms; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.rooms (
    id bigint NOT NULL,
    address character varying(255),
    approved_at timestamp(6) without time zone,
    area double precision NOT NULL,
    bathrooms_count integer,
    bookings_count integer,
    commission double precision,
    commission_rate double precision,
    contact_email character varying(255),
    contact_phone character varying(255),
    contract_url character varying(255),
    created_at timestamp(6) without time zone,
    dalali_id bigint,
    dalali_name character varying(255),
    description character varying(255),
    featured boolean,
    has_contract boolean,
    has_video boolean,
    image_count integer,
    interested_count integer,
    is_available boolean,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    owner_name character varying(255),
    posted_by bigint,
    price double precision NOT NULL,
    promoted boolean,
    property_type character varying(255),
    rejection_reason character varying(255),
    rented_at timestamp(6) without time zone,
    rooms_count integer,
    status character varying(255),
    title character varying(255),
    updated_at timestamp(6) without time zone,
    video_url character varying(255),
    view_count integer,
    property_id bigint,
    floor_number integer,
    unit_number character varying(255)
);


--
-- Name: rooms_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.rooms ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rooms_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id bigint NOT NULL,
    business_name character varying(255),
    commission_rate double precision,
    created_at timestamp without time zone,
    email character varying(255),
    email_verified boolean NOT NULL,
    fcm_token character varying(500),
    firebase_uid character varying(255),
    id_card_image character varying(255),
    last_login_at timestamp without time zone,
    license_image character varying(255),
    license_number character varying(255),
    location_area character varying(255),
    name character varying(255),
    password character varying(255),
    password_reset_token character varying(255),
    phone character varying(255),
    profile_image character varying(255),
    rating double precision,
    rejection_reason character varying(255),
    reset_token_expiry timestamp without time zone,
    role character varying(255),
    total_commission double precision,
    total_interested integer,
    total_properties_sold integer,
    total_transactions integer,
    total_views integer,
    verification_status character varying(255),
    verified_at timestamp(6) without time zone,
    CONSTRAINT users_role_check CHECK (((role)::text = ANY ((ARRAY['TENANT'::character varying, 'OWNER'::character varying, 'DALALI'::character varying, 'GUEST'::character varying, 'USER'::character varying, 'ADMIN'::character varying, 'SUPER_ADMIN'::character varying])::text[]))),
    CONSTRAINT users_verification_status_check CHECK (((verification_status)::text = ANY ((ARRAY['PENDING'::character varying, 'VERIFIED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: bookings; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.bookings (id, created_at, end_date, number_of_guests, special_requests, start_date, status, "timestamp", total_price, updated_at, room_id, user_id) FROM stdin;
\.


--
-- Data for Name: notification_tokens; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.notification_tokens (id, app_version, created_at, device_id, device_model, fcm_token, is_active, os_version, updated_at, user_id) FROM stdin;
\.


--
-- Data for Name: room_amenities; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.room_amenities (room_id, amenity) FROM stdin;
\.


--
-- Data for Name: room_images; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.room_images (room_id, image) FROM stdin;
\.


--
-- Data for Name: room_rules; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.room_rules (room_id, rule) FROM stdin;
\.


--
-- Data for Name: rooms; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.rooms (id, address, approved_at, area, bathrooms_count, bookings_count, commission, commission_rate, contact_email, contact_phone, contract_url, created_at, dalali_id, dalali_name, description, featured, has_contract, has_video, image_count, interested_count, is_available, latitude, longitude, owner_name, posted_by, price, promoted, property_type, rejection_reason, rented_at, rooms_count, status, title, updated_at, video_url, view_count) FROM stdin;
\.


--
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.users (id, business_name, commission_rate, created_at, email, email_verified, fcm_token, firebase_uid, id_card_image, last_login_at, license_image, license_number, location_area, name, password, password_reset_token, phone, profile_image, rating, rejection_reason, reset_token_expiry, role, total_commission, total_interested, total_properties_sold, total_transactions, total_views, verification_status, verified_at) FROM stdin;
\.


--
-- Name: bookings_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.bookings_id_seq', 1, false);


--
-- Name: notification_tokens_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.notification_tokens_id_seq', 1, false);


--
-- Name: rooms_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.rooms_id_seq', 10, true);


--
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- Name: bookings bookings_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT bookings_pkey PRIMARY KEY (id);


--
-- Name: notification_tokens notification_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_tokens
    ADD CONSTRAINT notification_tokens_pkey PRIMARY KEY (id);


--
-- Name: rooms rooms_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT rooms_pkey PRIMARY KEY (id);

--
-- Name: properties properties_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.properties
    ADD CONSTRAINT properties_pkey PRIMARY KEY (id);


--
-- Name: users uk6dotkott2kjsp8vw4d0m25fb7; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT uk6dotkott2kjsp8vw4d0m25fb7 UNIQUE (email);


--
-- Name: notification_tokens ukaa1wuihvcr8v2ga02o54m9vkw; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.notification_tokens
    ADD CONSTRAINT ukaa1wuihvcr8v2ga02o54m9vkw UNIQUE (fcm_token);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: rooms fk5tn2e1d1a3sgw0ipe2mhc2qyf; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT fk5tn2e1d1a3sgw0ipe2mhc2qyf FOREIGN KEY (dalali_id) REFERENCES public.users(id);


--
-- Name: bookings fkeyog2oic85xg7hsu2je2lx3s6; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fkeyog2oic85xg7hsu2je2lx3s6 FOREIGN KEY (user_id) REFERENCES public.users(id);


--
-- Name: room_rules fkkgne4jx07yaggiqir3oti4aq7; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_rules
    ADD CONSTRAINT fkkgne4jx07yaggiqir3oti4aq7 FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: room_amenities fkps6ofup9gxhn8juqvproxbaud; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_amenities
    ADD CONSTRAINT fkps6ofup9gxhn8juqvproxbaud FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: bookings fkrgoycol97o21kpjodw1qox4nc; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.bookings
    ADD CONSTRAINT fkrgoycol97o21kpjodw1qox4nc FOREIGN KEY (room_id) REFERENCES public.rooms(id);


--
-- Name: room_images fktky1jnwoh1hv50m263p2vlt0y; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room_images
    ADD CONSTRAINT fktky1jnwoh1hv50m263p2vlt0y FOREIGN KEY (room_id) REFERENCES public.rooms(id);

--
-- Name: rooms fk_room_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.rooms
    ADD CONSTRAINT fk_room_property FOREIGN KEY (property_id) REFERENCES public.properties(id);

--
-- Name: property_images fk_property_images_property; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.property_images
    ADD CONSTRAINT fk_property_images_property FOREIGN KEY (property_id) REFERENCES public.properties(id);


--
-- PostgreSQL database dump complete
--

